        if self.self_locked == "yes":
            if self.is_freeze == "false":
                if self.view_redact == "true":
                    if self.lock_screen == "no":
                        button_configs = [
                            {"image": self.icons['lock'], "command": self.lock_function, "tooltip": "Lock Page","instance_var":"Lock_button"},
                            {"image": self.icons['selectarrow'], "command": self.activate_selection_mode, "tooltip": "Zoom Selected Area","instance_var":"selectzoom_button"},
                            {"image": self.icons['refresh_pdf'], "command": self.refresh, "tooltip": "Refresh Document"},
                            # {"image": self.icons['load_pdf'], "command": self.load_pdf, "tooltip": "Load PDF"},
                            {"image": self.icons['new_window'], "command": lambda: self.create_duplicate_window(fileurl), "tooltip": "New Window", "instance_var":"new_window_button"},
                            {"image": self.icons['zoom_out'], "command": self.zoom_out, "tooltip": "Zoom Out"},
                            {"image": self.icons['zoom_in'], "command": self.zoom_in, "tooltip": "Zoom In"},
                            # {"image": self.icons['zoom_area'], "command": self.toggle_zoom_in_area_mode, "tooltip": "Zoom Area"},
                            # {"image": self.icons['highlight'], "command": self.enable_highlight_mode, "tooltip": "Highlight","instance_var":"highlight_button"},
                            {"image": self.icons['highlight'], "command": self.activate_Highlight_rectangle_tool, "tooltip": "Highlight","instance_var":"filled_highlight_rectangle_button"},
                            {"image": self.icons['sticky_note'], "command": self.toggle_sticky_note_mode, "tooltip": "Sticky Note", "instance_var":"sticky_note_button"},
                            {"image": self.icons['undo'], "command": self.undo_change, "tooltip": "Undo"},
                            {"image": self.icons['delete'], "command": self.enable_delete_annotation_mode, "tooltip": "Delete Annotation", "instance_var":"delete_button"},
                            {"image": self.icons['rotate_90'], "command": self.rotate_90clockwise, "tooltip": "Rotate 90° Right"},
                            {"image": self.icons['rotate_180'], "command": self.rotate_180clockwise, "tooltip": "Rotate 180° Right"},
                            {"image": self.icons['rotate_270'], "command": self.rotate_270clockwise, "tooltip": "Rotate 270° Right"},
                            {"image": self.icons['best_fit'], "command": self.best_fit, "tooltip": "Best Fit"},
                            {"image": self.icons['best_width'], "command": self.best_width, "tooltip": "Best Width"},
                            {"image": self.icons['best_height'], "command": self.best_height, "tooltip": "Best Height"},
                            {"image": self.icons['invert_colors'], "command": self.toggle_invert_colors, "tooltip": "Invert Colors", "instance_var":"invert_button"},
                            # {"image": self.icons['save_pdf'], "command": self.save_pdf_type2, "tooltip": "Save PDF"},
                            # Buttons with instance variables
                            {"image": self.icons['text'], "command": self.add_text_to_pdf, "tooltip": "Add Text", "instance_var": "text_button"},
                            {"image": self.icons['filled_text'], "command": self.add_text_with_background, "tooltip": "Add Text Stamp", "instance_var": "text_bg_button"},
                            {"image": self.icons['free_line'], "command": self.toggle_drawing, "tooltip": "Free Hand Line", "instance_var": "draw_button"},
                            {"image": self.icons['filled_polygon'], "command": self.toggle_filled_polygon_mode, "tooltip": "Draw Filled Polygon", "instance_var": "filled_polygon_button"},
                            {"image": self.icons['hollow_polygon'], "command": self.toggle_hollow_polygon_mode, "tooltip": "Draw Hollow Polygon", "instance_var": "hollow_polygon_button"},
                            {"image": self.icons.get('image'), "command": lambda: self.attach_image_to_pdf(), "tooltip": "Attach Image", "instance_var": "image_button"},
                            {"image": self.icons['straightline'], "command": self.activate_line_tool, "tooltip": "Draw Straight Line", "instance_var": "line_button"},
                            {"image": self.icons['arrow'], "command": self.activate_arrow_tool, "tooltip": "Draw Arrow", "instance_var": "arrow_button"},
                            {"image": self.icons['hollow_rectangle'], "command": self.activate_hollow_rectangle_tool, "tooltip": "Draw Hollow Rectangle", "instance_var": "hollow_rectangle_button"},
                            {"image": self.icons['filled_rectangle'], "command": self.activate_filled_rectangle_tool, "tooltip": "Draw Filled Rectangle", "instance_var": "filled_rectangle_button"},
                            {"image": self.icons['hollow_ellipse'], "command": self.activate_hollow_ellipse, "tooltip": "Draw Hollow Ellipse", "instance_var": "hollow_ellipse_button"},
                            {"image": self.icons['filled_ellipse'], "command": self.activate_filled_ellipse, "tooltip": "Draw Filled Ellipse", "instance_var": "filled_ellipse_button"},
                            # {"image": self.icons['redact'], "command": self.toggle_redaction_mode, "tooltip": "Add Redaction"},
                            # {"image": self.icons['removeredact'], "command": self.remove_black_boxes, "tooltip": "Remove Redaction"},
                            {"image": self.icons['redact'], "command": self.activate_black_rectangle_tool, "tooltip": "Add Redaction", "instance_var": "redact_button"},
                            {"image": self.icons['removeredact'], "command": self.enable_undo_blackrect, "tooltip": "Delete Redaction","instance_var":"deleteredact_button"},
                            {"image": self.icons['save_pdf'], "command": self.save_pdf, "tooltip": "Save PDF"},
                            # {"image": self.icons['redact'], "command": self.redraw_black_rectangles_from_db, "tooltip": "redraw from db"},
                            # {"image": self.icons['redact'], "command": self.redraw_black_rectangles_from_api, "tooltip": "redraw from api"},
                        ]
                    else:
                        button_configs = [
                            {"image": self.icons['unlock'], "command": self.lock_function, "tooltip": "Unlock Page","instance_var":"Lock_button"},
                            {"image": self.icons['zoom_out'], "command": self.zoom_out, "tooltip": "Zoom Out"},
                            {"image": self.icons['zoom_in'], "command": self.zoom_in, "tooltip": "Zoom In"},
                            {"image": self.icons['rotate_90'], "command": self.rotate_90clockwise, "tooltip": "Rotate 90° Right"},
                            {"image": self.icons['rotate_180'], "command": self.rotate_180clockwise, "tooltip": "Rotate 180° Right"},
                            {"image": self.icons['rotate_270'], "command": self.rotate_270clockwise, "tooltip": "Rotate 270° Right"},
                            {"image": self.icons['best_fit'], "command": self.best_fit, "tooltip": "Best Fit"},
                            {"image": self.icons['best_width'], "command": self.best_width, "tooltip": "Best Width"},
                            {"image": self.icons['best_height'], "command": self.best_height, "tooltip": "Best Height"},
                        ]
                else:
                    if self.lock_screen == "no":
                        button_configs = [
                            {"image": self.icons['lock'], "command": self.lock_function, "tooltip": "Lock Page","instance_var":"Lock_button"},
                            {"image": self.icons['selectarrow'], "command": self.activate_selection_mode, "tooltip": "Zoom Selected Area","instance_var":"selectzoom_button"},
                            {"image": self.icons['refresh_pdf'], "command": self.refresh, "tooltip": "Refresh Document"},
                            # {"image": self.icons['load_pdf'], "command": self.load_pdf, "tooltip": "Load PDF"},
                            {"image": self.icons['new_window'], "command": lambda: self.create_duplicate_window(fileurl), "tooltip": "New Window", "instance_var":"new_window_button"},
                            {"image": self.icons['zoom_out'], "command": self.zoom_out, "tooltip": "Zoom Out"},
                            {"image": self.icons['zoom_in'], "command": self.zoom_in, "tooltip": "Zoom In"},
                            # {"image": self.icons['zoom_area'], "command": self.toggle_zoom_in_area_mode, "tooltip": "Zoom Area"},
                            # {"image": self.icons['highlight'], "command": self.enable_highlight_mode, "tooltip": "Highlight","instance_var":"highlight_button"},
                            {"image": self.icons['highlight'], "command": self.activate_Highlight_rectangle_tool, "tooltip": "Highlight","instance_var":"filled_highlight_rectangle_button"},
                            {"image": self.icons['sticky_note'], "command": self.toggle_sticky_note_mode, "tooltip": "Sticky Note", "instance_var":"sticky_note_button"},
                            {"image": self.icons['undo'], "command": self.undo_change, "tooltip": "Undo"},
                            {"image": self.icons['delete'], "command": self.enable_delete_annotation_mode, "tooltip": "Delete Annotation", "instance_var":"delete_button"},
                            {"image": self.icons['rotate_90'], "command": self.rotate_90clockwise, "tooltip": "Rotate 90° Right"},
                            {"image": self.icons['rotate_180'], "command": self.rotate_180clockwise, "tooltip": "Rotate 180° Right"},
                            {"image": self.icons['rotate_270'], "command": self.rotate_270clockwise, "tooltip": "Rotate 270° Right"},
                            {"image": self.icons['best_fit'], "command": self.best_fit, "tooltip": "Best Fit"},
                            {"image": self.icons['best_width'], "command": self.best_width, "tooltip": "Best Width"},
                            {"image": self.icons['best_height'], "command": self.best_height, "tooltip": "Best Height"},
                            {"image": self.icons['invert_colors'], "command": self.toggle_invert_colors, "tooltip": "Invert Colors", "instance_var":"invert_button"},
                            # {"image": self.icons['save_pdf'], "command": self.save_pdf_type2, "tooltip": "Save PDF"},
                            # Buttons with instance variables
                            {"image": self.icons['text'], "command": self.add_text_to_pdf, "tooltip": "Add Text", "instance_var": "text_button"},
                            {"image": self.icons['filled_text'], "command": self.add_text_with_background, "tooltip": "Add Text Stamp", "instance_var": "text_bg_button"},
                            {"image": self.icons['free_line'], "command": self.toggle_drawing, "tooltip": "Free Hand Line", "instance_var": "draw_button"},
                            {"image": self.icons['filled_polygon'], "command": self.toggle_filled_polygon_mode, "tooltip": "Draw Filled Polygon", "instance_var": "filled_polygon_button"},
                            {"image": self.icons['hollow_polygon'], "command": self.toggle_hollow_polygon_mode, "tooltip": "Draw Hollow Polygon", "instance_var": "hollow_polygon_button"},
                            {"image": self.icons.get('image'), "command": lambda: self.attach_image_to_pdf(), "tooltip": "Attach Image", "instance_var": "image_button"},
                            {"image": self.icons['straightline'], "command": self.activate_line_tool, "tooltip": "Draw Straight Line", "instance_var": "line_button"},
                            {"image": self.icons['arrow'], "command": self.activate_arrow_tool, "tooltip": "Draw Arrow", "instance_var": "arrow_button"},
                            {"image": self.icons['hollow_rectangle'], "command": self.activate_hollow_rectangle_tool, "tooltip": "Draw Hollow Rectangle", "instance_var": "hollow_rectangle_button"},
                            {"image": self.icons['filled_rectangle'], "command": self.activate_filled_rectangle_tool, "tooltip": "Draw Filled Rectangle", "instance_var": "filled_rectangle_button"},
                            {"image": self.icons['hollow_ellipse'], "command": self.activate_hollow_ellipse, "tooltip": "Draw Hollow Ellipse", "instance_var": "hollow_ellipse_button"},
                            {"image": self.icons['filled_ellipse'], "command": self.activate_filled_ellipse, "tooltip": "Draw Filled Ellipse", "instance_var": "filled_ellipse_button"},
                            # {"image": self.icons['redact'], "command": self.toggle_redaction_mode, "tooltip": "Add Redaction"},
                            # {"image": self.icons['removeredact'], "command": self.remove_black_boxes, "tooltip": "Remove Redaction"},
                            {"image": self.icons['redact'], "command": self.activate_black_rectangle_tool, "tooltip": "Add Redaction", "instance_var": "redact_button"},
                            {"image": self.icons['removeredact'], "command": self.enable_undo_blackrect, "tooltip": "Delete Redaction","instance_var":"deleteredact_button"},
                            {"image": self.icons['save_pdf'], "command": self.save_pdf, "tooltip": "Save PDF"},
                            # {"image": self.icons['redact'], "command": self.redraw_black_rectangles_from_db, "tooltip": "redraw from db"},
                            # {"image": self.icons['redact'], "command": self.redraw_black_rectangles_from_api, "tooltip": "Show Redact"},
                            {"image": self.icons['show'], "command": self.toggle_redact_display, "tooltip": "Show / hide Redact","instance_var":"redacttoggle_button"},
                        ]
                    else:
                        button_configs = [
                            {"image": self.icons['unlock'], "command": self.lock_function, "tooltip": "Unlock Page","instance_var":"Lock_button"},
                            {"image": self.icons['zoom_out'], "command": self.zoom_out, "tooltip": "Zoom Out"},
                            {"image": self.icons['zoom_in'], "command": self.zoom_in, "tooltip": "Zoom In"},
                            {"image": self.icons['rotate_90'], "command": self.rotate_90clockwise, "tooltip": "Rotate 90° Right"},
                            {"image": self.icons['rotate_180'], "command": self.rotate_180clockwise, "tooltip": "Rotate 180° Right"},
                            {"image": self.icons['rotate_270'], "command": self.rotate_270clockwise, "tooltip": "Rotate 270° Right"},
                            {"image": self.icons['best_fit'], "command": self.best_fit, "tooltip": "Best Fit"},
                            {"image": self.icons['best_width'], "command": self.best_width, "tooltip": "Best Width"},
                            {"image": self.icons['best_height'], "command": self.best_height, "tooltip": "Best Height"},
                        ]
            else:
                button_configs = [
                        {"image": self.icons['lock'], "command": self.dummy_function, "tooltip": "Page is Locked","instance_var":"dummy_button","fg_color": "#d17a24","hover_color": "#b56e26"},
                        {"image": self.icons['zoom_out'], "command": self.zoom_out, "tooltip": "Zoom Out"},
                        {"image": self.icons['zoom_in'], "command": self.zoom_in, "tooltip": "Zoom In"},
                        {"image": self.icons['rotate_90'], "command": self.rotate_90clockwise, "tooltip": "Rotate 90° Right"},
                        {"image": self.icons['rotate_180'], "command": self.rotate_180clockwise, "tooltip": "Rotate 180° Right"},
                        {"image": self.icons['rotate_270'], "command": self.rotate_270clockwise, "tooltip": "Rotate 270° Right"},
                        {"image": self.icons['best_fit'], "command": self.best_fit, "tooltip": "Best Fit"},
                        {"image": self.icons['best_width'], "command": self.best_width, "tooltip": "Best Width"},
                        {"image": self.icons['best_height'], "command": self.best_height, "tooltip": "Best Height"},
                        {"image": self.icons['invert_colors'], "command": self.toggle_invert_colors, "tooltip": "Invert Colors", "instance_var":"invert_button"},
                    ]